/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example.producer.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ProducerApp
{

    public static void main(String[] args) {
        SpringApplication.run(ProducerApp.class, args);
    }
}
